apiVersion: v1
kind: Pod
metadata:
 name: busybox-pod
spec:
 volumes:
 - name: demo
   configMap:
     name: mycm4
 containers:
 - image: busybox
   name: busybox
   command: ["/bin/sh"]
   args: ["-c", "sleep 600"]
   volumeMounts:
   - name: demo
     mountPath: /mydata
