apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
       name: nginx-pod
       labels:
         app: nginx-app
    spec:
     containers:
     - name: nginx
       image: nginx
