apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-less
spec:
  tolerations:
  - key: "mysize"
    operator: "Equal"
    value: "large"
    effect: "NoExecute"
    tolerationSeconds: 60
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000"
