apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school-app
  template:
    metadata:
       name: school-pod
       labels:
         app: school-app
    spec:
     containers:
     - name: school-app
       image: mangeshabnave/cgi-app-v1
       livenessProbe:
        httpGet:
          path: /about.html
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
