apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limitrange
  namespace: default
spec:
  limits:
  - default:
      memory: 300Mi
      #cpu: 0.3
    defaultRequest:
      memory: 50Mi
      #cpu: 0.1
    type: Container
