apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limitrange
  namespace: dev
spec:
  limits:
  - default:
      memory: 30Mi
      #cpu: 0.3
    defaultRequest:
      memory: 10Mi
      #cpu: 0.1
    type: Container
