apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx
  name: mynginx-10
  namespace: dev
spec:
  containers:
  - image: nginx
    name: mynginx
    resources:
      limits:
        memory: 200Mi
      requests:
        memory: 10Mi
