apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
  namespace: dev
spec:
  containers:
  - image: nginx
    name: mypod
    resources:
     limits:
      memory: 400Mi
     requests:
       memory: 100Mi
