apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sts-demo
  template:
    metadata:
       name: nginx-pod
       labels:
         app: nginx-sts-demo
    spec:
     containers:
     - name: nginx
       image: nginx
