apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "demoserver"
            operator: In
            values:
            - "true"
  containers:
  - name: with-node-affinity
    image: nginx
